namespace: "alikins"
name: "collection_reqs_test"
version: "2.1111.5"
description: "a collection with requirements.yml"
authors: ["Adrian Likins"]
license: "GPL-3.0-or-later"
dependencies:
  - geerlingguy.gitlab
